# Generated by Django 4.1.8 on 2023-04-19 09:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import outdated.outdated.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "last_checked",
                    models.DateTimeField(
                        blank=True,
                        default=outdated.outdated.models.get_yesterday,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("PIP", "PIP"), ("NPM", "NPM")], max_length=10
                    ),
                ),
                (
                    "_latest",
                    models.CharField(
                        blank=True, editable=False, max_length=100, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="DependencyVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=100)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "dependency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outdated.dependency",
                    ),
                ),
            ],
            options={
                "ordering": ["release_date", "dependency__name", "version"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("repo", models.URLField(max_length=100, unique=True)),
                (
                    "dependency_versions",
                    models.ManyToManyField(blank=True, to="outdated.dependencyversion"),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="dependency",
            index=models.Index(fields=["name", "provider"], name="name_provider_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dependency",
            unique_together={("name", "provider")},
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("name__iexact", django.db.models.functions.text.Lower("name"))
                ),
                fields=("name",),
                name="unique_project_name",
            ),
        ),
        migrations.AddIndex(
            model_name="dependencyversion",
            index=models.Index(
                fields=["dependency", "version"], name="dependency_version_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dependencyversion",
            unique_together={("dependency", "version")},
        ),
    ]
