---

existingSecret: ~

# kubectl create secret generic outdated-secrets \
#         --namespace app-outdated \
#         --from-literal=DATABASE_PASSWORD=xyz \
#         --from-literal=SECRET_KEY=xyz \

# for using an external database set DATABASE_HOST and DATABASE_USER

api:
  replicaCount: 1
  image:
    repository: ghcr.io/adfinis/outdated/api
    pullPolicy: IfNotPresent
    tag: ~
  service:
    type: ClusterIP
    port: 8000

ember:
  image:
    repository: ghcr.io/adfinis/outdated/ember
    pullPolicy: IfNotPresent
    tag: ~
  service:
    type: ClusterIP
    port: 80

django:
  allowedHosts: "*"
  watchmanChecks: ~
  debug: "False"

oidc:
  host: "https://login.example.com"
  clientId: "example-outdated"
  realm: "example"

postgresql:
  enabled: false
  auth:
    username: outdated
    database: outdated

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: outdated.example.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: outdated-ember
              port:
                number: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: outdated-api
              port:
                number: 80

persistence:
  accessMode: ReadWriteOnce
  size: 2Gi
  storageClass: ""
  annotations: {}

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
