version: "3.9"
services:
  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  api:
    build: ./api
    user: "${UID:?Set UID env variable to your user id}"
    depends_on:
      - db
#TODO: add a proxy
volumes:
  dbdata:
