version: "3.9"
services:
  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  api:
    build: ./api
    user: "${UID:?Set UID env variable to your user id}"
    depends_on:
      - db
  ember:
    build:
      context: ./ember/

  caddy:
    image: caddy:2.6-alpine
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

volumes:
  dbdata:
  caddy_data:
  caddy_config:
