version: "3.9"
services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    depends_on:
      - db

volumes:
  dbdata:
