# Generated by Django 4.1.10 on 2023-08-09 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("schedule", models.DurationField()),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("first-warning", "first-warning"),
                            ("second-warning", "second-warning"),
                            ("third-warning", "third-warning"),
                            ("final-warning", "final-warning"),
                            ("first-alert", "first-alert"),
                            ("second-alert", "second-alert"),
                            ("third-alert", "third-alert"),
                            ("final-alert", "final-alert"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ("-schedule",),
                "unique_together": {("schedule", "template")},
            },
        ),
    ]
