# Generated by Django 5.0.3 on 2024-03-12 13:54

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

import outdated.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DependencySource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.CharField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("repo", outdated.models.RepositoryURLField(max_length=100)),
                (
                    "repo_type",
                    models.CharField(
                        choices=[
                            ("public", "public"),
                            ("access-token", "access-token"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("major_version", models.IntegerField()),
                ("minor_version", models.IntegerField()),
                ("end_of_life", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": [
                    "end_of_life",
                    "dependency__name",
                    "major_version",
                    "minor_version",
                ],
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("patch_version", models.IntegerField()),
                ("release_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": [
                    "release_version__end_of_life",
                    "release_version__dependency__name",
                    "release_version__major_version",
                    "release_version__minor_version",
                    "patch_version",
                ],
            },
        ),
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider",
                    models.CharField(
                        choices=[("PIP", "PIP"), ("NPM", "NPM")], max_length=10
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "unique_together": {("name", "provider")},
            },
        ),
        migrations.CreateModel(
            name="Maintainer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_primary", outdated.models.UniqueBooleanField(default=False)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintainers",
                        to="outdated.dependencysource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_project_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("repo"),
                name="unique_project_repo",
            ),
        ),
        migrations.AddField(
            model_name="dependencysource",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="outdated.project",
            ),
        ),
        migrations.AddField(
            model_name="releaseversion",
            name="dependency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="outdated.dependency"
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="release_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="outdated.releaseversion",
            ),
        ),
        migrations.AddField(
            model_name="dependencysource",
            name="versions",
            field=models.ManyToManyField(blank=True, to="outdated.version"),
        ),
        migrations.AlterUniqueTogether(
            name="maintainer",
            unique_together={("user", "source")},
        ),
        migrations.AlterUniqueTogether(
            name="releaseversion",
            unique_together={("dependency", "major_version", "minor_version")},
        ),
        migrations.AlterUniqueTogether(
            name="version",
            unique_together={("release_version", "patch_version")},
        ),
    ]
