# Generated by Django 3.2.16 on 2022-11-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20221110_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package_end_of_life_date',
            new_name='end_of_life_date',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_release_date',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_repo',
            new_name='repo',
        ),
        migrations.AlterField(
            model_name='project',
            name='packages',
            field=models.ManyToManyField(to='projects.Package'),
        ),
    ]
