# Generated by Django 3.2.16 on 2023-01-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outdated', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
    ]
