# Generated by Django 3.2.16 on 2023-01-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("outdated", "0002_alter_project_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dependencyversion",
            old_name="end_of_life_date",
            new_name="eol_date",
        ),
    ]
