# Generated by Django 3.2.16 on 2023-02-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("outdated", "0003_rename_end_of_life_date_dependencyversion_eol_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dependency",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="dependencyversion",
            options={"ordering": ["eol_date", "id"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name", "id"]},
        ),
    ]
