name: Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set UID
        run: echo "UID=$(id --user)" > .env
      - name: Lint the backend code
        run: make lint-backend

  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set UID
        run: echo "UID=$(id --user)" > .env
      - name: Build the containers
        run: docker compose up -d --build db api
      - name: Check for missing migrations
        run: docker compose exec -T api ./manage.py makemigrations --check --dry-run --no-input
      - name: Run backend tests
        run: make test-backend
