---
name: Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.12.0

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.12.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./api/
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/outdated/api:latest

      - name: Build Ember Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./ember/
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/outdated/ember:latest

      - name: Create kind cluster
        uses: helm/kind-action@v1

      - name: Load dev images into k8s
        run: kind load docker-image ghcr.io/${{ github.repository_owner }}/outdated/api ghcr.io/${{ github.repository_owner }}/outdated/ember --name chart-testing

      - name: Run chart-testing (install)
        run: ct --config=ct.yaml install
