name: Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push API Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./api/
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/outdated/api:latest

      - name: Build and Push Ember Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./ember/
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/outdated/ember:latest

  helm-chart:
    runs-on: ubuntu-latest
    needs:
      - release-container
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
      id-token: none
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Chart Metadata
        id: chartmeta
        run: echo version=0.0.0+$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.12.0

      - name: Package Chart
        run: helm package --version ${{ steps.chartmeta.outputs.version }} --app-version ${{ steps.chartmeta.outputs.version }} --destination=dist charts/outdated

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Chart
        run: helm push dist/*.tgz oci://ghcr.io/adfinis/outdated/helm