---
name: Schedule

on:
  schedule:
    - cron: 11 15 * * *
  workflow_dispatch:

jobs:
  scan-api:
    name: Scan api image
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: write
      statuses: none
      # needed for `cosign attest`
      id-token: write
    steps:
      - uses: adfinis/container-scanning-action@v0.2.6
        with:
          image-ref: ghcr.io/${{ github.repository }}/api
          token: ${{ secrets.GITHUB_TOKEN }}
          attest: true

  scan-ember:
    name: Scan ember image
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: write
      pull-requests: none
      repository-projects: none
      security-events: write
      statuses: none
      # needed for `cosign attest`
      id-token: write
    steps:
      - uses: adfinis/container-scanning-action@v0.2.6
        with:
          image-ref: ghcr.io/${{ github.repository }}/ember
          token: ${{ secrets.GITHUB_TOKEN }}
          attest: true
