name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-backend:
    name: "lint the backend"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Switch directory
        run: cd backend

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Run black
        run: poetry run black --check .

      - name: Run flake8
        run: poetry run flake8

  frontend-lint:
    name: "Lint the frontend"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Switch directory
        run: ls
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint

  test-frontend:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Switch directory
        run: cd frontend
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: yarn test
