name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: [ubuntu-latest]
    steps:
      - name: Echo something
        run: echo "something"
